<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>YT2MP3</RootNamespace>
    <AssemblyName>YT2MP3</AssemblyName>
    <ApplicationIcon>audiodisc_compactdisc_cd_audio_1586.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateManifests>true</GenerateManifests>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
    <Content Include="audiodisc_compactdisc_cd_audio_1586.ico" />
  </ItemGroup>
</Project>
